### ISSUE TITLE
有一个问题：whitelist 的代理问题

### ISSUE THREAD

**Issue by sullevy** [geekpi/SpechtLiteConf#3]
如果按照现在的顺序
  - type: list
    file: ~/.SpechtLite/whitelist
    adapter: direct
 - type: all
    adapter: proxy
先指定 directlist 后设置 proxy，那么可正常访问百度等网站，但无法访问 youtube 等网站
但是顺序反过来
 - type: all
    adapter: proxy
  - type: list
    file: ~/.SpechtLite/whitelist
    adapter: direct
就可以正常访问了 youtube，但我不确定百度是否走了代理。

**Comment by geekpi** [comment]
spechtlite规则匹配由上到下，后者相当于全局代理

**Comment by sullevy** [comment]
那就奇怪了，不知道为什么 白名单这种设置方式，其余走 proxy 没通！

**Comment by sullevy** [comment]
可能是 whitelist 文件过大的原因？
我换用 directlist 里面条目比较少不超过1000条，就能连接

**Comment by sullevy** [comment]
我更换了 whitelist 就可以了

**Comment by geekpi** [comment]
已经修复，请更新后重试

**Comment by gontthias** [comment]
修复后的whitelist仍然不能访问twitter等网站

**Comment by gontthias** [comment]
@sullevy 更换后的whitelist能不能分享下？
