### ISSUE TITLE
使用whitelist规则，不能访问外网

### ISSUE THREAD

**Issue by gontthias** [geekpi/SpechtLiteConf#5]
使用whitelist，国内网站可以正常访问，但是国外网站无法访问。
log如下：
2018/01/24 08:50:40:019  Request: nex.163.com Type: DirectAdapter Rule: \<DomainListRule>
2018/01/24 08:55:42:831  Request: twitter.com Type: DirectAdapter Rule:  \<DomainListRule>

经测试，删除whitelist里的内容，只保留 ”163\\.com “这一行，twitter就可以正常访问了。
2018/01/24 09:01:56:659  Request: twitter.com Type: SpeedAdapter Rule: \<AllRule>

经测试，也不是行数过多的问题，把”163\\.com “这一行复制成4万行，twitter仍然可以正常访问。

应该是whitelist里有跟twitter等匹配的行，但是我不知道是哪一行。
希望大神能够修改下whitelist。谢谢

**Comment by gontthias** [comment]
经测试，删除whitelist 19160行 er\\.com,可以访问twitter了。但是youtube、google还是访问不了。说明er\\.com 和twitter存在匹配关系。这是什么原理？求解释

**Comment by geekpi** [comment]
5cb9b9d7b27032ef2f6911dc3b6974082f02eef4

更新下配置试试

**Comment by gontthias** [comment]
更新配置后果然能用了，直接下载下来的whitelist有39863行，更新后的whitelist有37074行。谢谢大神指点。
